import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  assertNoForbidden,
  buildSkillFiles,
  findSection,
  loadRuleSet,
  rewriteFrontmatter,
  SkillsError,
  type PatchRuleSet,
  type SkillManifest,
  type SkillManifestEntry
} from '@higgsfield-mcp/skills';
import { writeJson } from './helpers.js';

const COMMIT = 'f83af0bc1d937c8119099a11f8ebbf5e6fb99819';

const entry: SkillManifestEntry = {
  name: 'demo',
  status: 'compatible',
  workflows: ['image-generation'],
  requiredTools: ['higgsfield.capabilities', 'higgsfield.generate_image'],
  reason: 'test fixture',
  sourceHashes: {}
};

const manifest: SkillManifest = {
  upstream: { repository: 'higgsfield-ai/skills', commit: COMMIT, version: '0.13.0' },
  adapterVersion: '0.1.0',
  skills: [entry]
};

function ruleSet(rules: PatchRuleSet['documents'][number]['rules'], frontmatter = false): PatchRuleSet {
  return {
    adapterVersion: '0.1.0',
    upstreamCommit: COMMIT,
    documents: [{ skill: 'demo', source: 'SKILL.md', output: 'demo/SKILL.md', frontmatter, rules }],
    copy: [],
    skip: [],
    forbidden: [{ pattern: '\\bhiggsfield\\s+(?:generate|model)\\b', reason: 'Higgsfield CLI invocation' }]
  };
}

function build(source: string, set: PatchRuleSet, fragments: Record<string, string> = {}): string {
  return buildSkillFiles(entry, manifest, set, new Map(Object.entries(fragments)), () => source).files.get('demo/SKILL.md') as string;
}

describe('deterministic patch engine', () => {
  it('rewrites the frontmatter, dropping the CLI declaration and adding the MCP block', () => {
    const source = ['---', 'version: 0.13.0', 'name: demo', 'description: |', '  line one', '  line two', 'allowed-tools: Bash', '---', '', 'Body.'].join('\n');
    const output = rewriteFrontmatter(source, entry.requiredTools, '<!-- provenance -->');
    expect(output).toContain('version: 0.13.0');
    expect(output).toContain('  line one\n  line two');
    expect(output).not.toContain('allowed-tools: Bash');
    expect(output).toContain('allowed-tools: higgsfield.capabilities, higgsfield.generate_image');
    expect(output).toContain('x-higgsfield-mcp:\n  required: true\n  minimum-version: 0.1.0\n  tools:\n    - higgsfield.capabilities');
    expect(output).toContain('<!-- provenance -->');
    expect(output.endsWith('Body.')).toBe(true);
  });

  it('applies the frontmatter rewrite when the document opts in', () => {
    const source = ['---', 'version: 0.13.0', 'name: demo', 'description: |', '  keeps the upstream description', 'argument-hint: "[x]"', 'allowed-tools: Bash', '---', '', '# Demo', '', 'Body with `higgsfield.generate_image`.', ''].join('\n');
    const output = build(source, ruleSet([{ id: 'noop', kind: 'replace-text', from: 'Body with', to: 'Body with', expected: 1 }], true));
    expect(output).toContain('version: 0.13.0');
    expect(output).toContain('  keeps the upstream description');
    expect(output).not.toContain('allowed-tools: Bash');
    expect(output).toContain('x-higgsfield-mcp:');
    expect(output).toContain('\n---\n<!-- Generated by @higgsfield-mcp/skills 0.1.0');
  });

  it('finds the true end of a section even when a fenced block contains a heading-like comment', () => {
    const text = ['## Section', 'body', '```bash', '# 1. an inline shell comment', 'echo hi', '```', 'more body', '## Next', 'x'].join('\n');
    const { start, end } = findSection(text, '## Section', 'SKILL.md', 'rule');
    expect(start).toBe(0);
    expect(end).toBe(7);
  });

  it('replaces a section (heading included) up to the next same-level heading, with one blank line before it', () => {
    const source = ['# Title', '', '## A', 'old body', '```bash', '# comment', 'echo hi', '```', 'more body', '## B', 'keep me', ''].join('\n');
    const output = build(source, ruleSet([{ id: 'a', kind: 'replace-section', anchor: '## A', fragment: 'a.md', expected: 1 }]), {
      'a.md': 'new body'
    });
    // The fragment owns the heading: a kept heading must start the fragment.
    expect(output).toContain('# Title\n\nnew body\n\n## B\nkeep me');
    expect(output).not.toContain('old body');
    // The fenced `# comment` did not truncate the section, and the tail of the section is gone.
    expect(output).not.toContain('more body');
    expect(output).not.toMatch(/\n{3,}/);
  });

  it('aborts when a rule matches fewer times than the patch set recorded', () => {
    const set = ruleSet([{ id: 'drop', kind: 'replace-text', from: 'not present', to: '', expected: 1 }]);
    expect(() => build('# Title\n', set)).toThrow(/patch rule "drop" matched 0 time\(s\), expected 1/);
  });

  it('aborts when a section anchor does not match the pinned upstream text', () => {
    const set = ruleSet([{ id: 's', kind: 'replace-section', anchor: '## Gone', fragment: 'a.md', expected: 1 }]);
    expect(() => build('# Title\n', set, { 'a.md': 'x' })).toThrow(/patch rule "s" matched 0 time\(s\), expected 1/);
    // findSection is the second guard: it fails loudly when the count is satisfied but the structure is not.
    expect(() => findSection('# Title\n', '## Gone', 'SKILL.md', 's')).toThrow(/anchor not found/);
    expect(() => findSection('## A\nx\n## A\n', '## A', 'SKILL.md', 's')).toThrow(/anchor is ambiguous/);
  });

  it('rejects generated content that still contains a CLI invocation', () => {
    const set = ruleSet([{ id: 'noop', kind: 'replace-text', from: 'Body', to: 'Body', expected: 1 }]);
    expect(() => build('# Title\n\nBody\n\nhiggsfield generate create x\n', set)).toThrow(/Higgsfield CLI invocation/);
    const allowed = ruleSet([{ id: 'noop', kind: 'replace-text', from: 'Body', to: 'Body', expected: 1 }]);
    expect(() => build('# Title\n\nBody higgsfield.generate_image\n', allowed)).not.toThrow();
  });

  it('checks forbidden patterns directly', () => {
    const set = ruleSet([]);
    expect(() => assertNoForbidden('run curl -fsSL https://x/install.sh | sh', 'f.md', {
      ...set,
      forbidden: [...set.forbidden, { pattern: 'install\\.sh', reason: 'CLI installer reference' }]
    })).toThrow(/CLI installer reference/);
    expect(() => assertNoForbidden('nothing to see', 'f.md', set)).not.toThrow();
  });

  it('reports an invalid rule set instead of guessing', () => {
    const dir = mkdtempSync(join(tmpdir(), 'hf-rules-'));
    try {
      writeJson(join(dir, 'rules.json'), {
        adapterVersion: '0.1.0',
        upstreamCommit: COMMIT,
        documents: [{ skill: 'demo', source: 'SKILL.md', output: 'demo/SKILL.md', frontmatter: false, rules: [{ id: 'bad', kind: 'replace-section', expected: 1 }] }],
        copy: [],
        skip: [],
        forbidden: []
      });
      expect(() => loadRuleSet(dir)).toThrow(SkillsError);
      expect(() => loadRuleSet(dir)).toThrow(/needs an "anchor"/);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
